### ISSUE TITLE
Front page nav items are almost invisible between hamburger and 1295 widths

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/cambodian-child-theme#100]
On width greater than needed for the hamburger menu (~800 px wide) to appear but less than 1295px, the nav menu drops down onto the image and is almost invisible camouflaged in the image. Reconsidering the media queries and maybe providing a mostly transparent background might help. 
![cohp-front-page-nav](https://github.com/BYU-ODH/cambodian-child-theme/assets/5042778/bf230cb3-fbe9-47a4-a80a-260dcbc1afb2)

**Comment by briancroxall** [comment]
Let's explore 

- [ ] setting the hamburger menu to trigger at a higher width (say, 1000 px) 
- [ ] shrinking the padding on the nav bar items
- [ ] lowering the font size of the nav items as the screen width decreases

**Comment by WorldsEndless** [comment]
Problem found: the old, wrong picture was actually uploaded for those people, so our code was not working because they had an image specified already. Deleting that image causes our default to correctly take effect. What remains is to make sure the default works on the single-interviewee page as well

**Comment by briancroxall** [comment]
Let's go with the hamburger-only option for simplicity's sake.

**Comment by briancroxall** [comment]
Let's go ahead and implement on prod.

**Comment by spencercheng** [comment]
Implemented on Production!

**Comment by briancroxall** [comment]
Looks great!
