### ISSUE TITLE
Investigate problems with `birth village` on interview page

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#102]
I don't know how often `birth village` shows up on interview pages since it's not information everyone has. But

- [x] Investigate the fact that the information is displaying on a different line
- [x] investigate the fact that the link seems to be pointing to an empty `[guid]` rather than anything else

![2023-11-30_15-54-41](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/4aafac42-86d5-4133-8d3a-c3b01dea878a)

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/16878abc-bb5b-4df0-99a0-16d10f61884f)
