### ISSUE TITLE
Can the site upgrade WordPress safely?

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/cambodian-child-theme#106]
Because the server just had a PHP upgrade, upgrading WordPress would be nice. This can be tried on staging; see if it destroys plugins the way the PHP upgrade has destroyed Cassify.

**Comment by WorldsEndless** [comment]
This might be a good reason to look into containerizing cohp

**Comment by briancroxall** [comment]
I think these are both interesting ideas, @WorldsEndless. Who should take ownership?
