### ISSUE TITLE
People with two interviews aren't displaying correctly

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#108]
Here are the two people that I know have multiple interviews

- [Ngin Sophorn](https://cambodianoralhistoryproject.byu.edu/interviewee/ngin-sophorn/)
- [Kim Sopheap](https://cambodianoralhistoryproject.byu.edu/interview/kim-sopheap-interview/)

**Comment by briancroxall** [comment]
Reference #77 to see sketches of how it should function

**Comment by spencercheng** [comment]
![Uploading image.png…]()
How does this look?

**Comment by briancroxall** [comment]
It's a good start. I think we might a bit of extra padding above the second interview and after the `Interview Documents`. 

I'm also curious about the positioning of the audio tracks. The original sketch called for the tracks to be parallel to the interview date. That might not be possible, but with this layout, it's unclear which audio track goes with which interview.

**Comment by WorldsEndless** [comment]
Interviews should have an over-arching container that binds them with their audio links, files, etc. Each interview should be in one div.

**Comment by spencercheng** [comment]
Not sure why the image doesn't align with the Image - will consult tory

**Comment by briancroxall** [comment]
This is on the same branch as #111. This is done, but #111 isn't. So I'm going to close this.
