### ISSUE TITLE
Experiment with putting the interviewee image on the left

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#111]
Then put any biographical information (if it exists) to the right of the image.

![2024-02-02_10-42-27](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/0b6993a4-31d9-42ae-87f7-4c207aaae95e)

**Comment by spencercheng** [comment]
@briancroxall is there anything you would like me to experiment on while we wait for expert opion?

**Comment by briancroxall** [comment]
@gossettphd: Any thoughts about this?

**Comment by briancroxall** [comment]
Waiting on me to talk with @gossettphd

**Comment by briancroxall** [comment]
More less implemented with #118
