### ISSUE TITLE
Add placeholder image to interviewee page, if there's no image for the person

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#112]
![2024-02-02_10-45-00](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/78adcd56-ab12-4b36-94ff-32a08d1d9164)
![2024-02-02_10-45-05](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/a150cd8f-b78c-4b5c-94bd-eb6a00127219)

**Comment by WorldsEndless** [comment]
and, to clarify on an issue we had recently, that image should be within the theme, NOT added as the image for each un-photographed person. Code determines when to put down the default image, not that an actual default is added as the image for people (which makes it very difficult to change the default image if needed)

**Comment by spencercheng** [comment]
what you mean is to put it in the media and pull the path right? @WorldsEndless

**Comment by WorldsEndless** [comment]
that's right -- the default image should NOT be added through the browser.

**Comment by briancroxall** [comment]
Looks good.
