### ISSUE TITLE
On interviewee page, change `Date` to `Interview Date` and stop printing "Interview" after the date

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#114]
![2024-02-09_10-44-53](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/87c5811d-209a-4544-9dfa-cc393b9fd5de)

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/c6baab3e-ba96-4300-8bb7-d4869ae26cdd)
Changed! I'll go ahead and probably implement on Production since its just a small change

**Comment by briancroxall** [comment]
Looks good!
