### ISSUE TITLE
Add "all interview materials" link to the `single-interviewee.php` template

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#119]
The old interview template had a link to `All Interview Materials` in Box. It needs to be added to the `single-interviewee.php` template.

![2024-06-07_16-04-59](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/278cfc22-5260-4698-abc7-b28cc39c1c74)

**Comment by spencercheng** [comment]
Just to Clarify - the link to the Box Folder is the URL to "All interview materials right?"

**Comment by briancroxall** [comment]
Yes. That's correct.

**Comment by briancroxall** [comment]
Looks good. Let's pull to prod.

**Comment by briancroxall** [comment]
Change `material` to `materials`.

**Comment by briancroxall** [comment]
Otherwise, this looks good.

**Comment by briancroxall** [comment]
Live on prod!
