### ISSUE TITLE
Move YouTube players to under interview information. 

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#120]
All interviews, whether they have a video or not, should use a standard photo of the interviewee so the page can have a consistent look and feel. YouTube embeds should be moved to sit under the information about the interview, and they allow for more standard width/height.

**Comment by spencercheng** [comment]
would you mind sharing the figma pages with again? Or if you could paste the images here, thank you!

**Comment by briancroxall** [comment]
I will work on a sketch.

**Comment by spencercheng** [comment]
Did we want to replace the recording if the Video is present?

**Comment by briancroxall** [comment]
This appears to be done.

**Comment by briancroxall** [comment]
Live on prod.
