### ISSUE TITLE
Experiment with converting big interview list to a tile layout

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#121]
Inspired by the work of @gossettphd and her student, let's see if we can get the big interview list to use a tile layout. I know that this is governed by FacetWP, so it might not be all that easy.

![2024-06-07_16-14-30](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/79b9d06d-ce8d-46cf-b661-4a1f8b38715f)

**Comment by briancroxall** [comment]
This looks like we've got a good start.

**Comment by spencercheng** [comment]
![image](https://github.com/user-attachments/assets/68ecb428-2a78-4b0d-b66c-26ff0e2dcc34)
I added it the code on prod since all the pics are broken on staging..

**Comment by spencercheng** [comment]
What are your thoughts, I've made it so you just keep scrolling 
https://humstaging.byu.edu/cambodianoralhistories/interviews/?fwp_paged=2

**Comment by spencercheng** [comment]
@briancroxall

**Comment by spencercheng** [comment]
just made more edits - used grid instead of flex

**Comment by briancroxall** [comment]
We should make the number of posts/interviews that is displaying a multiple of 3. Let's try 18?

**Comment by briancroxall** [comment]
Let's also explore whether it's possible to use a `more posts` button similar to the homepage for pagination, as long as it doesn't impact loading times.

**Comment by spencercheng** [comment]
![image](https://github.com/user-attachments/assets/9233a7af-7f39-4808-b8a7-53df7000e487)

**Comment by briancroxall** [comment]
So, let's go to only 9 people loading. Then a "show more" button that loads another 9 and gives you another "show more" button. ♾️

**Comment by spencercheng** [comment]
got it!

**Comment by briancroxall** [comment]
Looks good. Can't wait to see it live.

**Comment by briancroxall** [comment]
This is FacetWP code rather than something that happens in `style.css`, so @spencercheng will need to copy that over from staging when the new style sheet is live.

But copying isn't working right at the moment, so that will be something to investigate.

**Comment by spencercheng** [comment]
Implementing it on Production is proving harder than it should be. Looks like Jquery / Ajax is having some issues. What doesn't make sense is it works on Staging... - not sure what makes production different?

**Comment by briancroxall** [comment]
Looks like we're getting a critical error on the big Interview page on prod.

**Comment by spencercheng** [comment]
Okay checking right now

**Comment by spencercheng** [comment]
should be back now

**Comment by briancroxall** [comment]
Yes. It's working now. No tile layout of course.

**Comment by briancroxall** [comment]
Spencer spent most of his time on this issue this week. Doesn't seem to like his code that works on staging.

**Comment by briancroxall** [comment]
I wonder if some of the problems could be accounted for by the differences in our staging and prod environments.

**Comment by benrencher** [comment]
Is production reflecting what is on stage now? I'm happy to sit down with @spencercheng and see if we can figure out what is going on together.

**Comment by briancroxall** [comment]
@benrencher Not sure, entirely. The challenge here is that there is some CSS that governs things, but more of it is tucked inside the `listings` FacetWP settings.
![2024-09-16_13-20-12](https://github.com/user-attachments/assets/6cdbc800-7cda-4701-b844-03fa51149a97)

**Comment by spencercheng** [comment]
On staging, I have the following code on facetWp: 

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interviewee Directory</title>
    <link rel="stylesheet" href="https://cdn.datatables.net/plug-ins/preview/searchPane/dataTables.searchPane.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0p3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>
        .grid-container {
            display: grid;
            grid-template-columns: repeat(3, 1fr); /* 3 columns with equal width */
            gap: 15px; /* Space between items */
        }

        .grid-item {
            margin-bottom: 30px;
        }

        .grid-item img {
            width: 100%; /* Ensure images fill the container */
            height: auto; /* Maintain aspect ratio */
            max-height: 300px; /* Adjust based on your desired max height */
            object-fit: cover; /* Cover the container area */
        }

        .grid-item .name {
            text-align: center;
            margin-top: 10px;
        }

        .hidden-post {
            display: none;
        }

        @media (max-width: 768px) {
            .grid-container {
                grid-template-columns: repeat(2, 1fr); /* 2 columns for smaller screens */
            }
        }

        @media (max-width: 480px) {
            .grid-container {
                grid-template-columns: 1fr; /* 1 column for very small screens */
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="grid-container" id="grid-container">
            <?php 
            $initial_posts = new WP_Query([
                'post_type' => 'interviewee',
                'post_status' => 'publish',
                'posts_per_page' => 9, // Load the first 9 posts
                'paged' => 1,
            ]);

            if ($initial_posts->have_posts()) :
                while ($initial_posts->have_posts()) : $initial_posts->the_post(); ?>
                    <div class="grid-item">
                        <?php echo pods('interviewee', get_the_ID())->template('Interviewee Directory'); ?>
                    </div>
                <?php endwhile;
                wp_reset_postdata();
            endif; ?>
        </div>
        <div class="row">
            <div class="col-12 text-center">
                <button id="load-more" class="btn btn-primary" data-page="2">Show More</button>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
        jQuery(document).ready(function($) {
            $("#load-more").click(function() {
                var button = $(this);
                var page = button.data('page');
                var ajaxurl = "<?php echo admin_url('admin-ajax.php'); ?>";

                $.ajax({
                    url: ajaxurl,
                    type: 'POST',
                    data: {
                        action: 'load_more_posts',
                        paged: page
                    },
                    beforeSend: function() {
                        button.text('Loading...');
                    },
                    success: function(response) {
                        $("#grid-container").append(response);
                        button.data('page', page + 1);
                        button.text('Show More');

                        // If there are no more posts, hide the button
                        if (response.trim() === '') {
                            button.hide();
                        }
                    }
                });
            });
        });
    </script>
</body>
</html>
`

**Comment by spencercheng** [comment]
It somehow does not like Ajax and Jquery on production.

**Comment by benrencher** [comment]
@spencercheng I don't see a reference to a variable named "code" in the above. Also, when I load the production site, I see jQuery 3.7.1 being loaded from wp-includes/js/jquery/jquery.min.js?ver=3.7.1 so we don't need to include another reference to jQuery here (unless this is a plugin?). I think it is best for you to come in and we can work on figuring this out together.

**Comment by spencercheng** [comment]
That sounds good. Would Friday after my meeting(12:30PM) with Brian work?

**Comment by spencercheng** [comment]
perfect! See you at your office on Friday:)

**Comment by benrencher** [comment]
@briancroxall Spencer and I took a look at the code together and were unable to figure out why we are getting errors in production while staging works. My best guess is that there is a race condition that isn't an issue in Staging but causes a problem in production. I asked Spencer to revert the changes made in this branch so we can either start over from a point where we know the code works, or make the decision to scrap the inifniscroll thing and go back to pagination. It seems like a lot of time has been spent on this feature already and Spencer's time may be better used on other issues or projects. If we want to keep working on this one, we should refresh staging first and make sure that both servers are running on the same versions of php, wordpress, and all wordpress plugins.

**Comment by spencercheng** [comment]
@briancroxall We also mentioned reverting back to when I just had the grids and the paginations which I believe would solve the problem since it is not using Javascript.

**Comment by briancroxall** [comment]
I'm fine with reverting to the 9-person grid and pagination. Let's get it
done.

**Comment by spencercheng** [comment]
![image](https://github.com/user-attachments/assets/d532f3d8-815a-43f5-a22f-984168035a6a)
How does this look?

**Comment by spencercheng** [comment]
![image](https://github.com/user-attachments/assets/2a38f990-6cf6-4b5c-a8e5-954a5a9da5a5)
This is probably easier to gauge

**Comment by briancroxall** [comment]
Let's go with this and implement on prod.
