### ISSUE TITLE
Anchor the site title and two buttons closer to the lower left corner of the hero image

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#122]
Current
![2024-06-07_16-22-11](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/ea525139-0fdc-40d3-bdc2-56d584293eca)

What we are aiming for
![2024-06-07_16-21-20](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/36595b7f-af53-4f2e-b197-e67f27f34bb9)

**Comment by spencercheng** [comment]
looks like the front-page is being customized by wordpress - I will have to consult @WorldsEndless how edit it.

**Comment by briancroxall** [comment]
This is controlled in the theme's customize option with `Landing Page` -> `Slider`. So we'd need to find this portion in the parent theme and then see what is controlling the buttons and text and try to adapt it in either/both the child theme's `functions.php` or `style.css`.

**Comment by briancroxall** [comment]
Looks a lot better. Let's PR.
