### ISSUE TITLE
Add a `Recent News` and a `<hr>` to the home page above where the posts display

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#123]
![2024-06-07_16-23-31](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/14e11f2f-5eb8-4318-9785-7df52f72d9b4)

**Comment by spencercheng** [comment]
@briancroxall This doesn't seem to be done with php. Do you remember how to access this homepage?

**Comment by briancroxall** [comment]
In customize, `Landing page` -> `Featured content` -> `Posts` is what we used to get the posts showing up. 

I suspect that there is something in the original Septera theme that governs the featured content on the landing page. If we can find that function, we should be able to insert a PHP `echo` statement to the child theme's `functions.php` to print Recent Stories. And then we can give it a class and style it in the child theme.

**Comment by briancroxall** [comment]
Worth consulting with @jeremybrownebyu on PHP/WP interactions.

**Comment by briancroxall** [comment]
Based on my poking around the install of Septera I have at [https://briancroxall.net/f20dh](https://briancroxall.net/f20dh), I think we're looking for `landing-page.php`. If we create a version of that page in the child theme, I suspect we'll be able to find the right place to `echo` in the `<hr>` and text.

**Comment by spencercheng** [comment]
![image](https://github.com/user-attachments/assets/f3e2ac87-d473-4192-ba73-259ce4170b4f)

**Comment by briancroxall** [comment]
Let's change to `Recent News` rather than `Recent Stories` and then do a pull request.

**Comment by briancroxall** [comment]
Live on prod.
