### ISSUE TITLE
Shrink the font of the title on person pages

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#124]
![2024-07-11_14-12-13](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/6f5a14d8-f76b-4264-810f-d28645e177ed)

**Comment by spencercheng** [comment]
![image](https://github.com/user-attachments/assets/0a0b2dd9-0a2b-4528-be14-f580b4bedd02)

**Comment by briancroxall** [comment]
Fixed!
