### ISSUE TITLE
Even left and right margins on mobile

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#125]
![2024-07-11_14-12-55](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/b86b48c5-43df-4332-b157-e335cc73839c)

**Comment by spencercheng** [comment]
![image](https://github.com/user-attachments/assets/8a7fae86-0a08-4121-9424-90c3c7d1b5ab)

**Comment by briancroxall** [comment]
Looks great. Let's pull

**Comment by briancroxall** [comment]
Looks to be live on prod.
