### ISSUE TITLE
Investigate whether we can adjust the hero image on mobile so that the main face is centered

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#132]
![The Cambodian Oral History Project – Capturing Stories of the Generations](https://github.com/user-attachments/assets/aa4275f6-5f00-45ca-93ba-ec2f46e083d5)

**Comment by briancroxall** [comment]
Let's spend a maximum of an hour on this. If we go beyond that, we might just tell the team it's not going to happen.

**Comment by spencercheng** [comment]
Looks like some media queries we didn't write are causing the picture to be like that. 
`@media (max-width: 720px) {

	.lp-staticslider {
		max-height: 70vmax;
	}

	.lp-staticslider .lp-staticslider-image {
		/* max-height: 70vmax; */
		/* position: relative; */
		/* left: 50%; */
		/* -webkit-transform: translateX(-50%); */
		-ms-transform: translateX(-50%);
		/* transform: translateX(-50%); */
		/* max-width: none; */
		/* width: auto; */
	}

	.lp-staticslider .staticslider-sep { height: 1px; }

	body .lp-blocks.lp-blocks-rows-4 .lp-block,
	body .lp-blocks.lp-blocks-rows-3 .lp-block,
	body .lp-blocks.lp-blocks-rows-2 .lp-block {
		width: 96%;
		margin: 0 2% 3em;
	}

}`

**Comment by spencercheng** [comment]
I think this is worth us discussing what we should do - and how the image should look.

**Comment by spencercheng** [comment]
I had to change the parent theme.

**Comment by spencercheng** [comment]
![image](https://github.com/user-attachments/assets/04a8257e-123c-4d04-bc61-7149c2c30d9e)

**Comment by briancroxall** [comment]
Looks good.

**Comment by briancroxall** [comment]
This was merged, but it's not appearing on prod yet @spencercheng

**Comment by spencercheng** [comment]
@briancroxall  Is there a theme editor for COHP prod? I'm not finding it anywhere. I used the staging theme editor to comment out the styles that were being applied from a stylesheet I don't have.

**Comment by spencercheng** [comment]
We might have to push the septera theme? Because I'm checking my code files and I have the code commented out.

**Comment by briancroxall** [comment]
I suspect that John may have turned off the theme editor on prod for security reasons. On Sep 30, 2024, at 4:39 PM, Spencer Cheng ***@***.***> wrote:﻿
We might have to push the septera theme? Because I'm checking my code files and I have the code commented out.

**Comment by spencercheng** [comment]
Okay I will reach out to John and see what he can do!

**Comment by briancroxall** [comment]
So the problem is that the parent Septera theme has something that is causing this problem. Spencer hasn't been able to override that with the child theme CSS, possibly because it's just a deletion from the CSS rather than a modification. On staging, we are able to access the theme file editor and he can make the change to the parent theme there. But the theme file editor isn't available on prod.

**Comment by briancroxall** [comment]
This isn't a great solution because every time we update the parent theme, we would have to re-implement the deletion.

**Comment by spencercheng** [comment]
Javascript - Remove styling. (Create JS script )

**Comment by briancroxall** [comment]
Looks great!
