### ISSUE TITLE
Page titles on standalone pages should be left aligned

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#135]
Probably related in some way to #131  and #130.

![2024-09-13_10-36-54](https://github.com/user-attachments/assets/4081b458-25f7-4894-bebd-d50db66d6770)

**Comment by spencercheng** [comment]
Could I get a link to this?

**Comment by briancroxall** [comment]
https://cambodianoralhistoryproject.byu.edu/related-projects-and-books/

**Comment by briancroxall** [comment]
Live on prod.
