### ISSUE TITLE
Export Pods Data

### ISSUE THREAD

**Issue by kwoods8** [BYU-ODH/cambodian-child-theme#74]
Find a plugin or a method to export the data stored in Pods (e.g. all the information for individual interviewees). WordPress plugins seem to struggle with data that has been encoded in Pods.

**Comment by briancroxall** [comment]
It appears to be possible using the [WP All Export plugin](https://wordpress.org/plugins/wp-all-export/). The output is messy but consistent, so it'll be possible to script around it.
