### ISSUE TITLE
Write a new version of the interviewee page that displays interview information

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#77]
Before we get started with #76, I'd like to consider a different path. 

Everything in COHP is written with magic tags. That's the major explanation of why there are separate `interviewee` and `interview` pages. I think that the site would be simplified if we condensed these into a single page, and I suspect that we should be able to do that by rewriting the interviewee page in PHP. This would allow us to call different Pods to display.

What do you think, @spencercheng?

**Comment by spencercheng** [comment]
Do you mind sending the url links to the interviewee page as well as the interview page? @briancroxall

**Comment by briancroxall** [comment]
Do you mean an example of each?

**Comment by briancroxall** [comment]
- [interviewee page](https://humstaging.byu.edu/cambodianoralhistories/interviewee/%e1%9e%9c%e1%9f%89%e1%9e%b6%e1%9e%93%e1%9f%8b%e1%9e%93%e1%9e%85%e1%9e%b6%e1%9e%93%e1%9f%8b%e1%9e%92%e1%9e%b8-van-chanthy/)
- [interview page](https://humstaging.byu.edu/cambodianoralhistories/interview/%e1%9e%9c%e1%9f%89%e1%9e%b6%e1%9e%93%e1%9f%8b%e1%9e%93%e1%9e%85%e1%9e%b6%e1%9e%93%e1%9f%8b%e1%9e%92%e1%9e%b8-van-chanthy-interview/)

**Comment by briancroxall** [comment]
What the current **Interviewee** and **Interview** pages look like
![IMG_5736](https://user-images.githubusercontent.com/1005115/227369394-8a6846cf-3846-4df3-b4e4-06e542d19d19.jpg)

**Comment by briancroxall** [comment]
What a new, combined page should look like.
![IMG_5737](https://user-images.githubusercontent.com/1005115/227369778-27285681-4377-44cf-ba6e-b04acec5f32a.jpg)

**Comment by briancroxall** [comment]
The one problem with the above is that it doesn't really account for the possibility of multiple interviews, which we should account for. So maybe this is a better way to conceive of it.

We could have the `h2` display `Interview` or `Interviews` depending on whether there is more than one.
![IMG_5738](https://user-images.githubusercontent.com/1005115/227371857-6a2bb674-c1a2-4936-9d39-87133b6da5e4.jpg)

**Comment by spencercheng** [comment]
Add title, and fix styling

**Comment by WorldsEndless** [comment]
audio working even on dev:
``` html
 <div class="audio-player">
			<audio controls="">
				<source src="https://byu.box.com/shared/static/1h2hdu4p2i9fwcbqi44hrhx9ktdvzcuo.m4a" type="audio/mpeg">
				<source src="https://byu.box.com/shared/static/1h2hdu4p2i9fwcbqi44hrhx9ktdvzcuo.m4a" type="audio/x-m4a">
				<source src="https://byu.box.com/shared/static/1h2hdu4p2i9fwcbqi44hrhx9ktdvzcuo.m4a" type="audio/aac">
				Your browser does not support the audio element.
			</audio>		
		</div>
```

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/da92b025-bf07-48c7-9faa-0758e4380e1a)
How does this look?

**Comment by briancroxall** [comment]
Looks pretty good and very close to what I asked for. Seeing it now as a prototype, I wonder about moving the audio and the PDF icon to be next to the picture. Would that work on mobile?

**Comment by spencercheng** [comment]
most likely, I can give it a go - do you want it on the left or right side?

**Comment by briancroxall** [comment]
Hard to say. Perhaps I should ask their team for feedback first…On Sep 26, 2023, at 2:48 PM, Spencer Cheng ***@***.***> wrote:﻿
most likely, I can give it a go - do you want it on the left or right side?

**Comment by spencercheng** [comment]
I feel like right side makes more sense, but that's just my personal opinion.

**Comment by WorldsEndless** [comment]
Careful when positioning content on the sides. It adds complications for mobile. You want to work out the mobile story first, and then scale it up as appropriate to larger view ports.

**Comment by briancroxall** [comment]
- [ ] Let's align the Interviews header so it's at the same vertical space as the sound recording.

![2023-09-28_16-20-22](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/4240a48c-8880-4f71-99ad-2b96924f687d)

- [ ] Then try putting all the information in a single column on the left.
- [ ] Take screenshots of each and ask the team for their preference.

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/edfc0844-8857-4a05-9b1d-a46e3e01454d)
How does this look? I decreased the padding and margin between the picture so it looks closer together. That way we an account for 1 or multiple interviews.

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/41531423-0fb3-4ff3-8a4b-63125853402b)
Align to the left (of course I centered just because it looks weird)
Here's the version where it's aligned left no centering:
 
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/556ea7e7-0d57-450d-b462-ec5a52ab3ea2)

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/466f3857-b5e1-4a9f-9d1d-69f7d71fde0e)
Interview title aligned with audio

**Comment by briancroxall** [comment]
I've emailed the team with a request for feedback.

**Comment by briancroxall** [comment]
The team prefers this version. 
![2](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/5a7c0553-0e53-4e33-81f9-c1114b933ad7)

**Comment by briancroxall** [comment]
I think this looks pretty good!

**Comment by briancroxall** [comment]
Let's go for it

**Comment by spencercheng** [comment]
implemented on Production!

**Comment by briancroxall** [comment]
Doesn't appear to be working. There's no audio or links to any documents on the page.
![2023-10-25_11-23-00](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/6bd5df64-de68-4821-81b6-b08145f45b71)

**Comment by briancroxall** [comment]
Hmm. So it's working on some, like the site's poster person Him Hen.
![2023-10-25_11-26-28](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/d6a4093f-6b8a-48a3-8358-bf9f8f499b06)

**Comment by briancroxall** [comment]
It appears that Lily Theng is a video interview. So the YouTube preview isn't showing up.

**Comment by spencercheng** [comment]
Okay, I'll look into that!

**Comment by spencercheng** [comment]
I forget, what do we need to do for this ticket again? Or is this just related to #86 ? @briancroxall

**Comment by spencercheng** [comment]
Oh wait I think it was the youtube video right? Would you want to show the picture as well? Or if it has the youtube video, then show that?

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/fff6a44b-cf2b-4de4-a044-2259a05db68c)

**Comment by briancroxall** [comment]
I met with some of the team yesterday. They've suggested suppressing the interviewee image if there's a YouTube video.

**Comment by briancroxall** [comment]
Going to start breaking some related issues out into their own tickets so we can wrap this one up.

**Comment by spencercheng** [comment]
Done!

**Comment by spencercheng** [comment]
Should be on production!

**Comment by briancroxall** [comment]
Looks good!
