### ISSUE TITLE
Rewrite `Interviews with English Translations` page so that it displays interviewee images.

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#78]
[Interviews with English Translations](https://cambodianoralhistoryproject.byu.edu/interviews-with-english-translations/)
![2023-03-08_10-42-36](https://user-images.githubusercontent.com/1005115/223789210-d4d58cb5-f66a-44b1-aedd-fc7dd5d5cc0c.png)

I'm not convinced how easy this will be. I wonder whether we can use the templates in the theme for [the blog page](https://cambodianoralhistoryproject.byu.edu/) as a place to start from.

**Comment by WorldsEndless** [comment]
The pictures look like `interviewee.cropped_picture`

**Comment by spencercheng** [comment]
Where does Interview with English Translations get their data from? Is it just if there is a translations on an an interview pod?

**Comment by briancroxall** [comment]
Yes, that should be it. Interviews are hosted as PDFs on Box. A public link is created for them and then added to the Interview pod. On Sep 26, 2023, at 3:42 PM, Spencer Cheng ***@***.***> wrote:﻿
Where does Interview with English Translations get their data from? Is it just if there is a translations on an an interview pod?

**Comment by briancroxall** [comment]
I think I misunderstood. The English Translation page is created via a shortcode `[english]` in an Elementor page. The shortcode is defined in `functions.php`.

Of course, the implementation of #77 will mean that we need to rewrite this function since the interview pages will disappear.

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/73413085-4639-438b-b703-2097f79c14aa)
What I have so far - The image is broken because I just realized that the function is pulling the interviewee from the interviews pods and the interviews pods doesn't have an image of the interviewee.. i trying to figure out relationships with each other to no avail.

**Comment by briancroxall** [comment]
For the card, let's have
- picture
- interviewee's name

Both the picture and the name (or the whole card) should link to the interviewee.

**Comment by spencercheng** [comment]
Is there a placeholder image we can use for those that don't have an image available?

**Comment by spencercheng** [comment]
how does this look? 
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/96cf5972-88f1-4e5a-9624-e082ed53ccc6)

**Comment by briancroxall** [comment]
I think we should do the following:
- try to convert the images from rectangular to squares so we avoid the stretching that will happen when taking the photo we are using for the interview and moving them to this layout
- add pagination so we don't have to load too many photos

**Comment by briancroxall** [comment]
Let's trying using this for the placeholder: http://cambodianoralhistoryproject.byu.edu/wp-content/uploads/2019/05/No-Image.png

**Comment by spencercheng** [comment]
@briancroxall looks like some of the merge request had my changes on prod. I will work on this first and make the changes live asap.

**Comment by WorldsEndless** [comment]
There is a problem with the height of certain images that doesn't match others so the choice is between cropping them or squishing them. Until the stake holders weigh in, we can probably institute a top-anchored cropping of the images; at least on the two we see, that will be a harmless CSS change (for Keith or Rosemarie). Ultimately we need the data creators to handle standardization of image dimensions.

**Comment by spencercheng** [comment]
ex. 
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/8d314be5-b5b7-43e9-9c39-e4ac5a0e3106)

**Comment by WorldsEndless** [comment]
> Let's trying using this for the placeholder: http://cambodianoralhistoryproject.byu.edu/wp-content/uploads/2019/05/No-Image.png

also see pods pagination, https://docs.pods.io/code/pods/pagination/

**Comment by briancroxall** [comment]
I will communicate with the team about the images needing to be consistent in their sizing. 

It also appears that the images are not being responsive as quickly as I would expect while changing the size of the browser window.

**Comment by briancroxall** [comment]
Let's change the font for people's names to make it more like what you see for blog posts on the home page.
![2023-11-09_16-13-50](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/06f1ca75-065c-4d65-b934-c8804ab85ed7)

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/f577f893-7a57-4d7a-a6af-ebb16a2d92b2)
How is this for font-size and weight?

**Comment by briancroxall** [comment]
Weight looks good. I would still dial the size down a touch.

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/5c7aa610-12e7-4015-918e-b5f0e6e0412c)
How about now?

**Comment by spencercheng** [comment]
This is the pagination for the beginning of the page: 
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/7ae844e8-1857-4cc4-893d-7a6b9427123f)

Bottom of page:
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/0fc19d08-25f0-42c6-afca-26626de046c6)
Any styling reccomendations?

**Comment by briancroxall** [comment]
Looks good. Let's only display 9 per page so we don't have the extra row.

**Comment by briancroxall** [comment]
Go ahead and push to production with:

- [ ] nine per page
- [ ] the links going to `interviewee` rather than `interview` (which is what is happening at the present on both staging and prod)
- [ ] replacing the COHP logo with the blank person placeholder since the latter is square and the former is rectangular

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/e9843df0-ce17-4b6a-812b-f9f647661000)
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/3bd712c2-aa13-4f21-8ee8-ae95cb2ba012)

**Comment by spencercheng** [comment]
The changes have been implemented. However, the placeholder image seems to be cached. After talking with @WorldsEndless, seems like we just have to wait it out.

**Comment by WorldsEndless** [comment]
Caching will be on the WordPress side, and there is past art on dealing with/clearing those caches so you don't have to hope that waiting  will do the trick. It looks like this was a discussion with Rosemarie in the week of Oct. 9, and she might have some more to say about it. See some of the conversation and link at https://byu-odh.zulipchat.com/#narrow/stream/343414-PHP-Dev/topic/Disabling.20cache/near/395756429. I've also mentioned you in the conversation there.

**Comment by briancroxall** [comment]
It all looks good to me. (And I don't even hate the logo being there as the placeholder.)

Oddly, on [p6 of the interviews with English translations])https://cambodianoralhistoryproject.byu.edu/interviews-with-english-translations/?pg=6) there is one person with the standard placeholder image.
![2023-11-30_16-12-52](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/b1706612-a0b1-4e45-a532-214909c71e2f)
