### ISSUE TITLE
Investigate whether we can use a slider for birthdate range

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#79]
Should be similar to what we are doing for VPTJ publication start/end.

**Comment by briancroxall** [comment]
<img width="313" alt="2023-03-15_09-54-31" src="https://user-images.githubusercontent.com/1005115/225366775-0c80a887-0fe8-484a-b79f-4cf6054da62e.png">

**Comment by spencercheng** [comment]
Are we specifying it by the month or year? I'm assuming it's year, but double checking

**Comment by briancroxall** [comment]
Just the year.

**Comment by briancroxall** [comment]
![2023-03-23_11-25-13](https://user-images.githubusercontent.com/1005115/227287392-af61e51b-148a-4799-b46e-4fe2f5dbef3d.png)

**Comment by briancroxall** [comment]
Needs a label: `Birth year`
