### ISSUE TITLE
Site title's color has changed

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#82]
Current
![2023-05-18_12-09-28](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/6a4ec1fb-93e7-44ca-bc67-ee9b6f870942)

How it should look
![2023-05-18_12-15-29](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/45f0fd75-0551-4d9e-baa7-1075200b8796)

**Comment by KHayes98** [comment]
I was able to find the issue regarding the discrepancy between the staging and production sites, as well as fix the title color on the production site. When the privacy policy was input to the production page, they did it from the Wordpress backend side, and for some reason added in-line styling that overwrote the stylesheets. This caused the production site to look different than the staging site. Removing that styling (with John's permission) caused the site to revert to its original state with the correct title color. Here is what it looks like right now. Is this an acceptable solution Brian?
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/95643441/3a002ef1-a9ee-4ee1-9924-c762530a6a60)

**Comment by WorldsEndless** [comment]
You'll want to make sure you @ him te get this sent the him. @briancroxall

**Comment by briancroxall** [comment]
Looks great. I’ll close the ticket once I can check in tomorrow. On Jun 23, 2023, at 3:23 PM, KHayes98 ***@***.***> wrote:﻿
I was able to find the issue regarding the discrepancy between the staging and production sites, as well as fix the title color on the production site. When the privacy policy was input to the production page, they did it from the Wordpress backend side, and for some reason added in-line styling that overwrote the stylesheets. This caused the production site to look different than the staging site. Removing that styling (with John's permission) caused the site to revert to its original state with the correct title color. Here is what it looks like right now. Is this an acceptable solution Brian?
