### ISSUE TITLE
Need to change references to `guid` in `single-province.php` to `permalink`

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#83]
If you go to one of the locations (like [Banteay Mancheay](https://cambodianoralhistoryproject.byu.edu/province/banteay-meanchey/)) and click on individuals, you are sometimes redirected to humstaging instead of the person's profile on prod. 

This almost certainly comes from the reference to `guid` in the following code from [single-province.php](https://github.com/BYU-ODH/cambodian-child-theme/blob/master/single-province.php):
```
  <?php if (!empty($interviewees)) {
                    echo("<h3>List of Interviewees</h3>");
                    // echo("<ul>");
                    foreach ($interviewees as $interview){
                      echo "<li class='list'><a href='" . $interview['guid'] . "'>" . $interview['post_title'] . "</a></li>";

                    }
                    // echo("</ul>");
                } ?>
```

`single-province.php` should be rewritten to use `permalink` instead. This is largely identical to [a problem that arose in SLDSW](https://gitlab.com/BYU-ODH/sldsw/-/issues/86).

**Comment by briancroxall** [comment]
![2023-10-23_15-56-58](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/f254af8a-f54d-4c1a-8a80-d1cd3f75739f)

**Comment by briancroxall** [comment]
@spencercheng Let me know if you need access to the SLDSW repo. I don't think you're on our GitLab team yet.

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/be83eab1-340b-4838-b944-97ee3cdc596d)
I've written it this way - however, not sure if this is the fix

**Comment by WorldsEndless** [comment]
that fix from guid to permalink should do the trick. Thanks for tracking that fix, Brian. Spencer, does it actually work for you?

**Comment by spencercheng** [comment]
Should be implemented on Production!

**Comment by briancroxall** [comment]
Looks to be fixed. Thanks for the quick turnaround!
