### ISSUE TITLE
Rewrite Interviews with Video Pages so links go to Interviewee rather than Interviews

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#86]
https://cambodianoralhistoryproject.byu.edu/interviews-with-videos/

**Comment by spencercheng** [comment]
Should be working now! 
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/38880cf6-7394-47b0-8bcf-98ff6beb6000)

**Comment by spencercheng** [comment]
Should be on Production!

**Comment by briancroxall** [comment]
Nice work!
