### ISSUE TITLE
English translation icon is broken on new interviewee page

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#88]
![2023-11-01_11-14-04](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/264c6ba5-d266-44c6-bf2e-2c0214c03f11)

**Comment by spencercheng** [comment]
Ah yes, I fixed that in my pull request!

**Comment by briancroxall** [comment]
In #94

**Comment by spencercheng** [comment]
Should be good on production!

**Comment by briancroxall** [comment]
Looks good!
