### ISSUE TITLE
Add interviewer and link to interviewer to new interviewee page

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#89]
Something else that was missed in #77.

**Comment by spencercheng** [comment]
don't we have interviewer? We just need to add the link right?

**Comment by briancroxall** [comment]
You're right. We should change the name from being in bold to having a link.

**Comment by briancroxall** [comment]
Looks to be working. Let's implement on prod.

**Comment by briancroxall** [comment]
Looks like we still need to disable the bold on the name of the interviewer

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/4f60e5c1-81b9-44b2-acc1-e496920322c4)

**Comment by spencercheng** [comment]
push to production!

**Comment by briancroxall** [comment]
Looks good!

**Comment by briancroxall** [comment]
It looks like we lost the bolding that should be on the word `interviewer:`.

![2023-11-30_15-54-41](https://github.com/BYU-ODH/cambodian-child-theme/assets/1005115/a00aaeb3-13e7-4631-90d6-2e6c3c29f84c)

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/b12185d0-00a7-4050-9021-6357e356e1f5)
