### ISSUE TITLE
Investigate whether we can add interview topics to the facet on the Interviews page

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/cambodian-child-theme#92]
I don't remember why we never implemented this.

**Comment by briancroxall** [comment]
Perhaps it was because `Story included` is part of the **Interviews** pod and this facet is constructed from the **interviewee** pod.

**Comment by spencercheng** [comment]
According to your debugging data, the "topics" facet has nothing indexed in facet, so there is nothing for facet to display.

Can you double check that facet settings and re-save and re-index?

Also, please update to the latest Facet version - 4.2.7.

**Comment by spencercheng** [comment]
Seems like facetwp is filter based on the listing - which is filtering for Interviewee. However, the topics are on the Interviews pods.

**Comment by WorldsEndless** [comment]
did the test work, making a dummy page for the pod that owns the information and seeing if it populated the list right?

**Comment by spencercheng** [comment]
<link rel="stylesheet" href="https://cdn.datatables.net/plug-ins/preview/searchPane/dataTables.searchPane.min.css">
<link rel="stylesheet"  href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://kryogenix.org/code/browser/sorttable/sorttable.js"></script>


<style>
table.sortable th:not(.sorttable_sorted):not(.sorttable_sorted_reverse):not(.sorttable_nosort):after { 
    content: " \25B4\25BE" 
}
</style>

<div class="pane">          

<div class="table-responsive-sm">
<table class="display" style="width:100%" id="myTable">


    <thead>
	<tr>
  	    <th class="text-center sorttable_nosort"><h5></h5></th>
	    <th class="text-center"><h5>ឈ្មោះ<br/>Name</h5></th>
            <th class="text-center" id="content-desktop"><h5>អាយុពេលដែលសម្ភាស<br/>Age at Interview</h5></th>
	    <th class="text-center sorttable_nosort" id="content-desktop"><h5>អត្ថបទនៃការសម្ភាស<br/>Transcript</h5></th>
        </tr>
    </thead>
    <tbody>
     
       
<?php while ( have_posts() ): the_post(); ?>
  <?php echo pods( 'interviewee', get_the_id() )->template( 'Interviewee Directory' ); ?>
<?php endwhile; ?>



    </tbody>
</table>
</div>

**Comment by briancroxall** [comment]
Given how the data are structured and since we do not want to change that structure at this point, we are going to have to rely on the current versions of accessing interview topics rather than adding it into the search facets.

**Comment by briancroxall** [comment]
Since we can get the transcript appearing on the big interview list and the transcript comes from the **Interview** pod rather than the **interviewee** pod, could we do something similar to list the `story included` fields?

```
  

<tr>
			<td class="text-center align-middle interviewee-picture">
				<a href={@permalink}>
				 [if picture]
					 {@picture._img}
				
				 [else]
				  <img src="https://cambodianoralhistoryproject.byu.edu/wp-content/uploads/2019/05/No-Image.png"/>
				 [/if]
				</a>
			</td>
			<td class="text-center align-middle">
				<h6><a href="{@permalink}">{@post_title}</a></h6>
			</td>
			<td class="text-center align-middle" id="content-desktop">
			[if participated_in_interview]
				[each participated_in_interview]
					[if interviewees_age]
					{@interviewees_age}
					[/if]
				[/each]
			[/if]
			</td>
			<td class="text-center align-middle" id="content-desktop">
				[if participated_in_interview]
					[each participated_in_interview]
						[if transcript_file]
							<a href="{@permalink}"><img src="https://cambodianoralhistoryproject.byu.edu/wp-content/uploads/2019/08/KhmerFile-1.png" style="max-width: 50px;"/></a>
						[/if]
					[/each]
				[/if]
			</td>
		</tr>
```

So something like
``` 
[if participated_in_interview]
  [each participated_in_interview}
    [if story_included]
      [each story_included]
```

**Comment by spencercheng** [comment]
On staging for COHP, seems like the listing option is broken( Deprecated) - Would you like me to try this on Prod? 

![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/59315bad-3d75-4364-8aff-def404706774)

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/b7dc0ffc-df5d-49fd-9f1c-df048967b017)

I was able to output the topics, but It seems to be outputting them all at once, so I haven't found a way to link it properly.

**Comment by WorldsEndless** [comment]
beware -- prod should have the same issues, it just isn't displaying them. So fix it on humstaging and that fix will probably be good for Prod, too

**Comment by briancroxall** [comment]
Here are some ideas for displaying the interview topics:

- [ ] We should change the header from `story included` to `interview topic(s)`
- [ ] For the link we can do one of the following:
  - Not link the text
  - Link to the [interview topics](https://cambodianoralhistoryproject.byu.edu/interview-topics/) page
  - try to figure out how to link to each topic individually (but I don't know how important that is)
- [ ] Try to widen the column just a little so things don't stack up quite so tall

**Comment by spencercheng** [comment]
Looks like FacetWp pulls from the Pods table as a whole, rather then the interview templates.

**Comment by briancroxall** [comment]
Here is the text for the column title:

ប្រធានបទនៅក្នុងបទសម្ភាសន៍

**Comment by briancroxall** [comment]
So add the text to the column title on staging, and then I'll talk with the team to see if it's something that they want to implement on prod.

**Comment by spencercheng** [comment]
![image](https://github.com/BYU-ODH/cambodian-child-theme/assets/89827794/1395bff9-7e5e-4267-ab5f-58444a41fc65)
On staging!

**Comment by briancroxall** [comment]
It appears that staging's responsive features are broken.

**Comment by spencercheng** [comment]
Yea it's kind of wonky - seems like on prod the mobile version isn't all that responsive as well

**Comment by briancroxall** [comment]
I'll talk to the team about this feature.

**Comment by briancroxall** [comment]
At this point, I think we are just going to close this issue since it's not something we can implement.
